name: de.scynostv.movecraft2.core
version: '${project.version}'
main: de.scynostv.movecraft2.core
api-version: 1.18
depend: [ InventoryApi ]
authors: [ ChiAkuma, CG ]
description: Movecraft 2 is a adaption of the old movecraft plugin.
